In [2]:
import torch

In [4]:
float_tensor = torch.FloatTensor([[1,2], [3,4]])

In [5]:
float_tensor

tensor([[1., 2.],
        [3., 4.]])

In [6]:
int_tensor = torch.LongTensor([[1,2], [3,4]])

In [7]:
int_tensor

tensor([[1, 2],
        [3, 4]])

In [8]:
float_tensor = torch.FloatTensor(3, 4)

In [9]:
float_tensor

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39]])

In [10]:
float_tensor = torch.FloatTensor(3, 4, 2)

In [11]:
float_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [12]:
import numpy as np

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [14]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
t = torch.from_numpy(arr)

In [16]:
t

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [17]:
t = torch.FloatTensor(2, 3)

In [18]:
t

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
a = t.numpy()

In [20]:
a

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [21]:
long_tensor = float_tensor.long()

In [22]:
float_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [23]:
long_tensor

tensor([[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]])

In [24]:
long_tensor.float()

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [25]:
t = torch.LongTensor(3, 4, 2)

In [26]:
t

tensor([[[3761461379779803682, 7003490141203675446],
         [4048789048668599352, 7003153724954850105],
         [3760891863108038713, 2464089332780249393],
         [8385534776637005868, 7287422581096149113]],

        [[8241417393971357048, 2459013923121950821],
         [7308604897285731189, 8243121639892466210],
         [2459013922786468206, 2481042943426913651],
         [3905803286562873402, 4062582649488041273]],

        [[4123098442383254068, 4134638929399997235],
         [2459013922044458544, 2459029315949715812],
         [3256719550727729202, 3760851176851257649],
         [4121412891023847994, 8512401619610645810]]])

In [27]:
t.shape

torch.Size([3, 4, 2])

In [28]:
t.size()

torch.Size([3, 4, 2])

In [29]:
t.size(0)

3

In [30]:
t.size(1)

4

In [31]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:
torch.rand(2, 3)

tensor([[0.2936, 0.3822, 0.7827],
        [0.2408, 0.1331, 0.6520]])

In [33]:
t = torch.rand(4, 4)

In [34]:
t

tensor([[0.2829, 0.9848, 0.0104, 0.0079],
        [0.9518, 0.4461, 0.5311, 0.7024],
        [0.0676, 0.9696, 0.3033, 0.7448],
        [0.3908, 0.5395, 0.1163, 0.6393]])

In [35]:
b = t.view(2, 8)

In [36]:
b

tensor([[0.2829, 0.9848, 0.0104, 0.0079, 0.9518, 0.4461, 0.5311, 0.7024],
        [0.0676, 0.9696, 0.3033, 0.7448, 0.3908, 0.5395, 0.1163, 0.6393]])

In [37]:
t.storage().data_ptr() == b.storage().data_ptr()

True

In [38]:
b[0][0] = 3.14

In [39]:
print(b[0][0])
print(t[0][0])

tensor(3.1400)
tensor(3.1400)


In [40]:
a = torch.arange(4.)

In [41]:
a

tensor([0., 1., 2., 3.])

In [42]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [43]:
b = torch.tensor([[0, 1], [2, 3]])

In [44]:
b

tensor([[0, 1],
        [2, 3]])

In [45]:
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

In [54]:
x = torch.zeros(2, 1, 2, 1, 2)

In [47]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [48]:
y = torch.squeeze(x)

In [49]:
y.size()

torch.Size([2, 2, 2])

In [50]:
x.storage().data_ptr() == y.storage().data_ptr()

True

In [55]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [56]:
y = torch.squeeze(x, 0)

In [57]:
y.size()

torch.Size([2, 1, 2, 1, 2])

In [58]:
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [59]:
y = torch.squeeze(x, 1)

In [60]:
y

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [ ]:
#183쪽 unsqeeze()부터

In [3]:
x = torch.tensor([1, 2, 3, 4])

In [4]:
x

tensor([1, 2, 3, 4])

In [5]:
x.shape

torch.Size([4])

In [6]:
y = torch.unsqueeze(x, 0)

In [7]:
y

tensor([[1, 2, 3, 4]])

In [8]:
y.shape

torch.Size([1, 4])

In [9]:
z = torch.unsqueeze(x, 1)

In [10]:
z

tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
z.shape

torch.Size([4, 1])

In [12]:
x = torch.randn(2, 3)

In [13]:
x

tensor([[-0.4305,  0.1195,  0.6990],
        [ 0.4092, -2.4644,  1.9569]])

In [14]:
torch.transpose(x, 0, 1)

tensor([[-0.4305,  0.4092],
        [ 0.1195, -2.4644],
        [ 0.6990,  1.9569]])

In [15]:
x = torch.randn(3, 4)

In [16]:
x

tensor([[-0.7188,  0.3929,  0.3353, -0.1191],
        [-0.0978,  1.1760, -2.0307, -1.8109],
        [-0.1363, -0.3402,  0.6981, -0.4977]])

In [17]:
indices = torch.tensor([0, 2])

In [21]:
torch.index_select(x, 0, indices)

tensor([[-0.7188,  0.3929,  0.3353, -0.1191],
        [-0.1363, -0.3402,  0.6981, -0.4977]])

In [22]:
torch.index_select(x, 1, indices)

tensor([[-0.7188,  0.3353],
        [-0.0978, -2.0307],
        [-0.1363,  0.6981]])

In [23]:
a = torch.arange(10).reshape(5, 2)

In [24]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [26]:
x = torch.randn(2, 3)

In [27]:
x

tensor([[ 0.3970, -1.2287,  0.1385],
        [-0.7905,  0.2146,  1.2883]])

In [28]:
torch.cat((x, x, x), 0)

tensor([[ 0.3970, -1.2287,  0.1385],
        [-0.7905,  0.2146,  1.2883],
        [ 0.3970, -1.2287,  0.1385],
        [-0.7905,  0.2146,  1.2883],
        [ 0.3970, -1.2287,  0.1385],
        [-0.7905,  0.2146,  1.2883]])

In [29]:
torch.cat((x, x, x), 1)

tensor([[ 0.3970, -1.2287,  0.1385,  0.3970, -1.2287,  0.1385,  0.3970, -1.2287,
          0.1385],
        [-0.7905,  0.2146,  1.2883, -0.7905,  0.2146,  1.2883, -0.7905,  0.2146,
          1.2883]])

In [31]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [32]:
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [33]:
z = torch.stack([x, y])

In [34]:
z

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [35]:
z.size()

torch.Size([2, 3, 3])

In [ ]:
#260쪽부터 기울기 소실과 활성 함수

learing rate : 학습률
DNN : 심층신경망(linear layer 여러개 쌓고 활성함수를 이용하여 구성)
Chain Rule : 연쇄법칙 -> 역전파 학습