In [2]:
import torch

In [3]:
float_tensor = torch.FloatTensor([[1,2], [3,4]])

In [4]:
float_tensor

tensor([[1., 2.],
        [3., 4.]])

In [5]:
int_tensor = torch.LongTensor([[1,2], [3,4]])

In [6]:
int_tensor

tensor([[1, 2],
        [3, 4]])

In [7]:
float_tensor = torch.FloatTensor(3, 4)

In [8]:
float_tensor

tensor([[1.0286e-38, 1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39, 8.4490e-39]])

In [9]:
float_tensor = torch.FloatTensor(3, 4, 2)

In [10]:
float_tensor

tensor([[[1.0561e-38, 1.0653e-38],
         [4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39],
         [1.0561e-38, 6.7041e-39]],

        [[1.1112e-38, 9.5511e-39],
         [1.0102e-38, 9.0918e-39],
         [1.0469e-38, 8.4490e-39],
         [1.0102e-38, 9.2755e-39]],

        [[8.9082e-39, 1.0653e-38],
         [1.0837e-38, 1.0561e-38],
         [9.2755e-39, 9.9184e-39],
         [1.0286e-38, 1.6956e-43]]])

In [11]:
import numpy as np

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
t = torch.from_numpy(arr)

In [15]:
t

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [16]:
t = torch.FloatTensor(2, 3)

In [17]:
t

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 6.8664e-44]])

In [18]:
a = t.numpy()

In [19]:
a

array([[0.0e+00, 0.0e+00, 0.0e+00],
       [0.0e+00, 0.0e+00, 6.9e-44]], dtype=float32)

In [20]:
long_tensor = float_tensor.long()

In [21]:
float_tensor

tensor([[[1.0561e-38, 1.0653e-38],
         [4.1327e-39, 8.9082e-39],
         [9.8265e-39, 9.4592e-39],
         [1.0561e-38, 6.7041e-39]],

        [[1.1112e-38, 9.5511e-39],
         [1.0102e-38, 9.0918e-39],
         [1.0469e-38, 8.4490e-39],
         [1.0102e-38, 9.2755e-39]],

        [[8.9082e-39, 1.0653e-38],
         [1.0837e-38, 1.0561e-38],
         [9.2755e-39, 9.9184e-39],
         [1.0286e-38, 1.6956e-43]]])

In [22]:
long_tensor

tensor([[[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0],
         [0, 0]]])

In [23]:
long_tensor.float()

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [24]:
t = torch.LongTensor(3, 4, 2)

In [25]:
t

tensor([[[8317708060514804060, 6661498323808383533],
         [8750595692532037471, 8750595679395671924],
         [8458424653570010996, 7599644542608108649],
         [8750595726975657070, 8031145638923235188]],

        [[7165916827689182066, 7021788497416905052],
         [7021786293846105188, 7161130589148702068],
         [3328265013910131813, 3833748767860879459],
         [          892548408,                   0]],

        [[                  0,                   0],
         [                  0,                   0],
         [                  0,                   0],
         [                  0,                   0]]])

In [26]:
t.shape

torch.Size([3, 4, 2])

In [27]:
t.size()

torch.Size([3, 4, 2])

In [28]:
t.size(0)

3

In [29]:
t.size(1)

4

In [30]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
torch.rand(2, 3)

tensor([[0.2036, 0.6947, 0.5769],
        [0.5803, 0.3158, 0.0306]])

In [32]:
t = torch.rand(4, 4)

In [33]:
t

tensor([[0.3315, 0.7891, 0.1072, 0.5195],
        [0.5714, 0.3666, 0.3369, 0.3517],
        [0.3195, 0.9978, 0.2226, 0.7637],
        [0.5633, 0.3287, 0.2292, 0.9186]])

In [34]:
b = t.view(2, 8)

In [35]:
b

tensor([[0.3315, 0.7891, 0.1072, 0.5195, 0.5714, 0.3666, 0.3369, 0.3517],
        [0.3195, 0.9978, 0.2226, 0.7637, 0.5633, 0.3287, 0.2292, 0.9186]])

In [36]:
t.storage().data_ptr() == b.storage().data_ptr()

True

In [37]:
b[0][0] = 3.14

In [38]:
print(b[0][0])
print(t[0][0])

tensor(3.1400)
tensor(3.1400)


In [39]:
a = torch.arange(4.)

In [40]:
a

tensor([0., 1., 2., 3.])

In [41]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [42]:
b = torch.tensor([[0, 1], [2, 3]])

In [43]:
b

tensor([[0, 1],
        [2, 3]])

In [44]:
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

In [45]:
x = torch.zeros(2, 1, 2, 1, 2)

In [46]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [47]:
y = torch.squeeze(x)

In [48]:
y.size()

torch.Size([2, 2, 2])

In [49]:
x.storage().data_ptr() == y.storage().data_ptr()

True

In [50]:
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [51]:
y = torch.squeeze(x, 0)

In [52]:
y.size()

torch.Size([2, 1, 2, 1, 2])

In [53]:
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [54]:
y = torch.squeeze(x, 1)

In [55]:
y

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [56]:
#183쪽 unsqeeze()부터

In [57]:
x = torch.tensor([1, 2, 3, 4])

In [58]:
x

tensor([1, 2, 3, 4])

In [59]:
x.shape

torch.Size([4])

In [60]:
y = torch.unsqueeze(x, 0)

In [61]:
y

tensor([[1, 2, 3, 4]])

In [62]:
y.shape

torch.Size([1, 4])

In [63]:
z = torch.unsqueeze(x, 1)

In [64]:
z

tensor([[1],
        [2],
        [3],
        [4]])

In [65]:
z.shape

torch.Size([4, 1])

In [66]:
x = torch.randn(2, 3)

In [67]:
x

tensor([[-1.2966, -0.2425, -0.1929],
        [-0.5282, -0.1543, -0.6435]])

In [68]:
torch.transpose(x, 0, 1)

tensor([[-1.2966, -0.5282],
        [-0.2425, -0.1543],
        [-0.1929, -0.6435]])

In [69]:
x = torch.randn(3, 4)

In [70]:
x

tensor([[ 0.6768, -0.7877, -0.4666,  1.6592],
        [ 1.4737, -1.2905, -0.3251, -1.0322],
        [-0.4607, -0.3825, -0.3303, -2.3291]])

In [71]:
indices = torch.tensor([0, 2])

In [72]:
torch.index_select(x, 0, indices)

tensor([[ 0.6768, -0.7877, -0.4666,  1.6592],
        [-0.4607, -0.3825, -0.3303, -2.3291]])

In [73]:
torch.index_select(x, 1, indices)

tensor([[ 0.6768, -0.4666],
        [ 1.4737, -0.3251],
        [-0.4607, -0.3303]])

In [74]:
a = torch.arange(10).reshape(5, 2)

In [75]:
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [76]:
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [77]:
x = torch.randn(2, 3)

In [78]:
x

tensor([[ 0.3188, -0.5239, -0.2773],
        [-0.3754, -1.4180,  0.2380]])

In [79]:
torch.cat((x, x, x), 0)

tensor([[ 0.3188, -0.5239, -0.2773],
        [-0.3754, -1.4180,  0.2380],
        [ 0.3188, -0.5239, -0.2773],
        [-0.3754, -1.4180,  0.2380],
        [ 0.3188, -0.5239, -0.2773],
        [-0.3754, -1.4180,  0.2380]])

In [80]:
torch.cat((x, x, x), 1)

tensor([[ 0.3188, -0.5239, -0.2773,  0.3188, -0.5239, -0.2773,  0.3188, -0.5239,
         -0.2773],
        [-0.3754, -1.4180,  0.2380, -0.3754, -1.4180,  0.2380, -0.3754, -1.4180,
          0.2380]])

In [81]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [82]:
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [83]:
z = torch.stack([x, y])

In [84]:
z

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [85]:
z.size()

torch.Size([2, 3, 3])

In [86]:
#260쪽부터 기울기 소실과 활성 함수

learing rate : 학습률
DNN : 심층신경망(linear layer 여러개 쌓고 활성함수를 이용하여 구성)
Chain Rule : 연쇄법칙 -> 역전파 학습

#딥러닝 회귀 실습

In [87]:
from sklearn.datasets import load_boston
boston_house = load_boston()

c:\Users\mu070\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (

In [88]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.DataFrame(boston_house.data, columns=boston_house.feature_names)
scaler = StandardScaler()
scaler.fit(df.values[::])
df.values[::] = scaler.transform(df.values[::])
df['TARGET'] = boston_house.target
df

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.419782  0.284830 -1.287909 -0.272599 -0.144217  0.413672 -0.120013   
1   -0.417339 -0.487722 -0.593381 -0.272599 -0.740262  0.194274  0.367166   
2   -0.417342 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
3   -0.416750 -0.487722 -1.306878 -0.272599 -0.835284  1.016303 -0.809889   
4   -0.412482 -0.487722 -1.306878 -0.272599 -0.835284  1.228577 -0.511180   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.413229 -0.487722  0.115738 -0.272599  0.158124  0.439316  0.018673   
502 -0.415249 -0.487722  0.115738 -0.272599  0.158124 -0.234548  0.288933   
503 -0.413447 -0.487722  0.115738 -0.272599  0.158124  0.984960  0.797449   
504 -0.407764 -0.487722  0.115738 -0.272599  0.158124  0.725672  0.736996   
505 -0.415000 -0.487722  0.115738 -0.272599  0.158124 -0.362767  0.434732   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  TARGET  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.075562    24.0  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.492439    21.6  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.208727    34.7  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.361517    33.4  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -1.026501    36.2  
..        ...       ...       ...       ...       ...       ...     ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.418147    22.4  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.500850    20.6  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.983048    23.9  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.865302    22.0  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.669058    11.9  

[506 rows x 14 columns]

In [96]:
import torch

data_numpy = torch.from_numpy(df.values).float()
x = data_numpy[:, -1] # 독립 변수
y = data_numpy[:,-1:] # 타겟 변수

# Train / Validation / Test 분할 비율
split_ratio = [0.6, 0.2, 0.2]

# 분할 데이터별 필요한 데이터 수 설정
train_cnt = int(data_numpy.size(0)*split_ratio[0])
valid_cnt = int(data_numpy.size(0)*split_ratio[1])
test_cnt = data_numpy.size(0) - train_cnt - valid_cnt
cnts = [train_cnt, valid_cnt, test_cnt]

# 데이터 갯수 만큼 랜덤하게 인덱스 번호 생성
indices = torch.randperm(data_numpy.size(0))

# 독립변수와 다겟변수로부터 랜덤하게 생성한 인덱스 순서대로 추출
x = torch.index_select(x, dim=0, index=indices)
y = torch.index_select(y, dim=0, index=indices)

# Train / Validation / Test 분할 비율에 맞게 데이터 분할
x = x.split(cnts, dim=0)
y = y.split(cnts, dim=0)

# 분할된 데이터셋 크기 확인
for x_i, y_i in zip(x, y):
    print(x_i.size(), y_i.size())

#분할 결과
print(f'Train:{train_cnt}, Valid:{valid_cnt}, Test:{test_cnt} samples')

torch.Size([303]) torch.Size([303, 1])
torch.Size([101]) torch.Size([101, 1])
torch.Size([102]) torch.Size([102, 1])
Train:303, Valid:101, Test:102 samples


#학습 모델 구축

In [97]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 딥러닝 모델 생성 pytorch의 nn.Module 활용하는 방법
class MyModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        #은닉층 설계
        self.linear1 = nn.Linear(input_dim, 32)
        self.linear2 = nn.Linear(32, 16)
        self.linear3 = nn.Linear(16, 8)
        self.linear4 = nn.Linear(8, 4)
        self.linear5 = nn.Linear(4, output_dim)
        self.act = nn.ReLU()

    def forward(self, x):
        #객체 호출 시 입력 텐서 크기:|x| = (batch_size, input_dim)
        h = self.act(self.linear1(x))
        h = self.act(self.linear2(h))
        h = self.act(self.linear3(h))
        h = self.act(self.linear4(h))
        y = self.linear5(h)

        return y

In [106]:
import torch.nn as nn

#pytorch nn.Sequential 활용 방법
input_dim = x[0].size(-1)
output_dim = y[0].size(-1)

model_sequencial = nn.Sequential(
    nn.Linear(x[0].size(-1), 5),
    nn.LeakyReLU(),
    nn.Linear(5,5),
    nn.LeakyReLU(),
    nn.Linear(5,5),
    nn.LeakyReLU(),
    nn.Linear(5,5),
    nn.LeakyReLU(),
    nn.Linear(5,5),
    nn.LeakyReLU(),
    nn.Linear(3, y[0].size(-1))
)

print(model_sequencial)

Sequential(
  (0): Linear(in_features=303, out_features=5, bias=True)
  (1): LeakyReLU(negative_slope=0.01)
  (2): Linear(in_features=5, out_features=5, bias=True)
  (3): LeakyReLU(negative_slope=0.01)
  (4): Linear(in_features=5, out_features=5, bias=True)
  (5): LeakyReLU(negative_slope=0.01)
  (6): Linear(in_features=5, out_features=5, bias=True)
  (7): LeakyReLU(negative_slope=0.01)
  (8): Linear(in_features=5, out_features=5, bias=True)
  (9): LeakyReLU(negative_slope=0.01)
  (10): Linear(in_features=3, out_features=1, bias=True)
)
